### ISSUE TITLE
luosimao 服务不能正常使用

### ISSUE THREAD

**Issue by greatghoul** [saberma/china_sms#24]
```
/Users/greatghoul/.rvm/gems/ruby-2.0.0-p481/gems/china_sms-0.0.7/lib/china_sms.rb:14:in `const_get': uninitialized constant ChinaSMS::Service::Luosimao (NameError)
	from /Users/greatghoul/.rvm/gems/ruby-2.0.0-p481/gems/china_sms-0.0.7/lib/china_sms.rb:14:in `use'
	from /Users/greatghoul/Workspace/nologo/config/initializers/china_sms.rb:1:in `<top (required)>'
```

**Comment by guxiaobai** [comment]
gem 'china_sms' :github => 'saberma/china_sms'
